### ISSUE TITLE
Type definition does not contain valid languages for a contact

### ISSUE THREAD

**Issue by Skudo** [infopark/webcrm_sdk#8]
Using `infopark_webcrm_sdk` version `1.0.3`, the type definition you get from `Crm::Type#standard_attribute_definitions` does not contain valid values for a contact's `language` attribute:

```ruby
type = Crm::Type.find(:contact)
type.standard_attribute_definitions[:language]
=> {"attribute_type"=>"enum", "create"=>true, "mandatory"=>true, "read"=>true, "title"=>"Language", "update"=>true, "valid_values"=>[]}
```

The type definition in general knows about valid languages though:

```ruby
type.languages
=> ["de", "en"]
```

The lack of `valid_values` eventually leads to wrong validation results, when you're trying to validate an object with `Crm::Type#standard_attribute_definitions` and `Crm::Type#attribute_definitions`.

**Comment by apepper** [comment]
This is not an SDK, but an API issue, since the API does not report `valid_values` for languages.

@Skudo: can you reopen an issue at https://github.com/infopark/omc/issues ?

**Comment by Skudo** [comment]
kk, done.
